# Please change the name of this file to
# `config.yml` and modify it to use it as your camera configuration.
config: 
  camera_type: webcam # can be `webcam | feed | serial`.
  feed_url: "" # something like `rtsp://192.168.blah.blah`
  serial_device: "" # something like `DN04T9FH` (unix) or `COM3` (win)
  
